apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
  labels:
    volume: app-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/app-data
    
