apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-pod
  name: nginx-pod
spec:
  nodeSelector: 
    kubernetes.io/hostname: "gke-k8-cluster-1-default-pool-c8cc922c-t6kf"
  volumes:
  - name: "data"
    hostPath:
      path: "/data"
  containers:
  - image: nginx:1.14.0
    name: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: "data"
    ports:
    - containerPort: 80
      name: http
      protocol: TCP

